#ifndef DS4_SERVER_TESTS_INTERNAL_H
#define DS4_SERVER_TESTS_INTERNAL_H
/* server 测试拆分共享头: 断言基元 + 跨测试文件共享的 helper 声明。
 * tests/ds4_test.c 与全部 tests/server_tests_*.c 都从这里进入 server 内部接口。 */
#include "../src/server/server_internal.h"

extern int test_failures;
void test_assert(bool cond, const char *file, int line, const char *expr);
#define TEST_ASSERT(expr) test_assert((expr), __FILE__, __LINE__, #expr)

void test_assert(bool cond, const char *file, int line, const char *expr);
void test_tool_schema_order_from_anthropic_schema(void);
void test_tool_schema_order_from_openai_tools(void);
void test_tool_schema_order_from_responses_tool_search(void);
void test_responses_function_named_tool_search_stays_function_call(void);
void test_responses_namespace_tool_schemas_restore_wire_namespace(void);
void test_responses_input_tool_search_output_loads_tools(void);
void test_responses_input_tool_search_output_rejects_bad_tools(void);
void test_responses_input_function_call_namespace_round_trips_to_dsml(void);
void test_responses_output_sends_tool_search_call_item(void);
tool_calls make_swapped_bash_call(void);
tool_schema_orders make_bash_order(void);
char *read_socket_text(int fd);
void test_context_length_error_uses_protocol_standard_shape(void);
void test_cors_headers_are_opt_in(void);
void test_cors_preflight_response_is_no_content(void);
void test_cors_sse_headers(void);
void test_chat_page_route_serves_html(void);
void test_chat_page_missing_file_is_404(void);
void test_anthropic_live_stream_sends_incremental_blocks(void);
void test_anthropic_tool_stream_sends_live_tool_use(void);
void test_anthropic_usage_reports_cache_details(void);
void test_openai_tool_stream_sends_incremental_text(void);
void test_openai_stream_usage_reports_cache_details(void);
void test_responses_usage_reports_cache_details(void);
void test_openai_chat_stream_splits_reasoning_without_tools(void);
void test_openai_tool_stream_sends_partial_arguments(void);
void test_openai_tool_stream_waits_for_incomplete_tool_tags(void);
void test_openai_tool_stream_sends_partial_raw_arguments(void);
void test_openai_tool_stream_holds_partial_dsml_entities(void);
void test_openai_tool_stream_holds_partial_utf8_arguments(void);
void test_openai_tool_stream_handles_multiple_calls(void);
void test_streaming_holds_partial_utf8(void);
void test_request_defaults_use_min_p_filtering(void);
void test_reasoning_effort_mapping(void);
void test_api_thinking_controls_parse(void);
void test_render_think_max_prompt_prefix(void);
void test_render_matches_official_v41_encoding(void);
void test_render_matches_official_spaced_dsml_tools(void);
void test_parse_spaced_dsml_tool_calls(void);
void test_openai_stream_spaced_dsml_tool_call(void);
void test_syntax_greedy_spaced_dsml(void);
void test_render_non_thinking_prompt_closes_think(void);
void test_render_drops_old_reasoning_without_tools(void);
void test_render_preserves_reasoning_with_tools(void);
void test_render_chat_prompt_text_renders_tools_before_system(void);
void test_dsml_tool_args_preserve_call_order(void);
void test_openai_tool_args_preserve_call_order(void);
void test_anthropic_thinking_and_tool_args_preserve_call_order(void);
void test_parse_short_dsml_and_canonical_suffix(void);
void test_dsml_parser_recovers_loose_nested_parameters(void);
void test_tool_parse_failure_returns_recoverable_finish(void);
void test_invalid_dsml_tool_error_suffix_includes_system_prompt(void);
void test_thinking_dsml_is_not_executable_before_think_close(void);
void test_thinking_dsml_after_think_close_is_executable(void);
void test_thinking_unclosed_returns_reasoning_not_content(void);
void test_tool_checkpoint_suffix_is_future_prompt_canonical(void);
void test_tool_checkpoint_minifies_json_parameters(void);
void test_tool_memory_replays_sampled_dsml(void);
void test_anthropic_tool_memory_replays_sampled_dsml(void);
void test_anthropic_live_tail_renders_tool_results_only(void);
void test_anthropic_tool_result_id_validation(void);
void test_anthropic_full_replay_allows_unknown_live_id(void);
void test_anthropic_tool_use_parses_before_role(void);
void test_mm_registry_text_encode_and_b64(void);
void test_anthropic_image_block_renders_encoder_text(void);
void test_anthropic_tool_result_mcp_blocks(void);
void test_mcp_tool_schema_names_roundtrip(void);
void test_tool_checkpoint_canonicalization_gate_exact_replay(void);
void test_responses_live_tail_renders_tool_outputs_only(void);
void test_responses_tool_output_id_validation(void);
void test_responses_stateless_tool_replay_requires_reasoning(void);
void test_responses_visible_suffix_matches_client_replay(void);
void test_exact_dsml_tool_replay_can_be_disabled(void);
void test_dsml_decode_state_separates_structure_and_payload(void);
void test_tool_memory_max_ids_prunes_oldest(void);
void test_tool_separator_whitespace_is_not_content(void);
void test_dsml_prompt_escapes_tool_supplied_text(void);
void test_stop_list_parses_all_sequences(void);
void test_stop_list_streaming_holds_and_trims_stop_text(void);
void test_json_skip_has_nesting_limit(void);
void test_model_metadata_clamps_completion_to_context(void);
void test_client_socket_nonblocking_flag(void);
void test_thinking_state_tracks_prompt_and_generated_tags(void);
void test_thinking_checkpoint_remember_gate(void);
void test_tool_marker_state_ignores_orphan_end(void);
void test_canonical_rewrite_rebuilds_when_live_tail_changes(void);
void test_kv_cache_store_len_uses_configured_boundary(void);
void test_kv_cache_chat_anchor_uses_last_user_before_assistant(void);
void test_kv_cache_chat_anchor_ignores_multiturn_tail(void);
void test_kv_cache_continued_uses_aligned_frontiers(void);
void test_kv_cache_cold_store_suppresses_duplicate_continued_boundary(void);
void test_kv_cache_file_size_must_fit_budget(void);
void test_sha1_bytes_hex_matches_known_vector(void);
void test_kv_stub_file(const char *dir, const char *sha, uint8_t reason, uint32_t tokens, uint32_t hits, uint64_t last_used, uint64_t payload_bytes);
void test_kv_text_stub_file(const char *dir, const char *text, uint8_t reason, uint32_t tokens, uint64_t payload_bytes);
void test_kv_cache_lookup_uses_longest_text_prefix(void);
void test_kv_cache_lookup_rejects_wrong_model(void);
void test_kv_cache_lookup_rejects_stale_payload_abi(void);
void test_kv_tool_map_filters_by_dsml_text(void);
void test_kv_tool_map_restores_before_prompt_render(void);
void test_kv_cache_eviction_values_fresh_snapshots(void);
void test_kv_cache_eviction_prefers_anchor_reason(void);
void test_kv_cache_eviction_makes_room_before_store(void);
void test_kv_cache_eviction_ignores_oversize_incoming(void);
void test_kv_cache_eviction_prefers_superseded_continued_prefix(void);
void test_kv_cache_eviction_keeps_smaller_context_prefix(void);
void test_kv_cache_eviction_score_decays_stale_hits(void);
void test_kv_cache_eviction_decayed_hits_tie_break_by_age(void);
void test_kv_cache_eviction_keeps_aligned_continued_frontiers(void);
void test_thinking_checkpoint_canonical_matches_future_prompt(void);
void test_thinking_canonical_empty_content(void);
void test_thinking_canonical_multi_turn(void);
void test_thinking_canonical_with_tools_preserves_reasoning(void);
void test_thinking_canonical_non_thinking_mode_noop(void);
/* 监控(tests/server_tests_monitor.c) */
void test_monitor_request_lifecycle_reaches_metrics(void);
void test_monitor_recent_requests_default_twelve_or_all(void);
void test_monitor_prometheus_text_uses_vllm_names(void);
void test_monitor_accept_header_selects_prometheus(void);
void test_monitor_http_route_selects_json_or_prometheus(void);
void test_monitor_page_route_serves_html(void);
void ds4_server_unit_tests_run(void);
#endif /* DS4_SERVER_TESTS_INTERNAL_H */
