#!/bin/bash
# code_corpus_build.sh — 编程侧车的语料构建(Mac 侧跑; 2026-09-26 用户令"添加一个编程的侧车, 用开源数据集切两份:
#   一份做路由反修+增益反修, 一份验证五指标"; 同日追加"语料要齐全")。与 fin_corpus_build.sh 平行: 一个领域一个构建脚本。
#
# 产物: gguf-tools/data/corpus/code/code_<语言>.jsonl —— 一个文件 = 一个域, 一行 = 一个源文件 {"text": 原文}。
#   域 = 数据集的全部 30 种语言(见下面 DOMAINS 表), 每个域都必须凑满 TARGET_BYTES, 缺一个就硬停。
#   来源: huggingface codeparrot/github-code-clean(apache-2.0, GitHub 真实源文件, 已去重/去自动生成)。
#   按分片号 0,1,2… 依次读, 所有域都满额就停; 读到 MAX_SHARDS 片还有域不满 = 硬停(不产缺域的语料)。
#   为什么不用 datasets-server 的按语言取行接口: 09-26 实测 TypeScript/GO/Rust/Shell 四个语言配置在服务端建索引超时
#   ("job exceeded maximum duration"), 取不到; 直接下 parquet 分片按 language 列过滤, 所有域同一条路。
#
# 为什么是 .jsonl 而不是金融那样的 .txt: 金融把文内换行折成空格无损(散文), 代码折了就不是代码 —— Python 的缩进是
#   语法, "\n    " 和 " " 分词也完全不同, 拿折过的文本拟合侧车等于在一种不存在的分布上解。json 一行一篇、换行原样保留;
#   amp_campaign.sh idshalf 的目录模式按扩展名认: .txt 整行即原文, .jsonl 取 "text" 字段。
# 为什么一个仓库只收一个文件(跨全部域): 同一仓库的文件共享命名/风格/许可证头, 分到拟合份和判决份两边 = 判决份
#   见过拟合份的近亲, 五指标偏乐观。每仓一篇 ⇒ 整篇只进一份的纪律自动升级成整仓只进一份。
# 为什么按分片顺序取就算均匀: 分片内不按仓库排序(第 0 片 126,925 个文件来自 90,904 个仓库)。
#   最稀的几种语言单片很少(第 0 片 Julia 72 个文件 302 KB、Dockerfile 183 个 191 KB), 所以要多读几片。
# 为什么 TARGET_BYTES 是 600 KB 而不是金融的 1.2 MB: 两份各只从每域取 512 token(每份 15360 = 30 × 512),
#   600 KB ≈ 15 万 token 已是 300 倍余量; 1.2 MB 要 Dockerfile 读十几片, 多出来的量一个 token 都抽不到。
# 为什么剥掉开头的版权/许可证注释: 09-26 在第 0 片实测, 带许可证头的文件 C 64.5% / C++ 61.0% / Java 48.2% /
#   Rust 44.0% / Go 37.8%, 按全文件字符占 0.5~6.3%; 单篇截到 DOC_CAP_CHARS 后头部占比只会更高 —— 这部分 token
#   是在拟合许可证文本。只剥"文件开头连续注释块且含 copyright/license/spdx"这一种, 正文里的注释一个不动。
# 为什么最长行门槛是 1000 不是 300: Markdown/TeX/HTML 一个段落就是一行, 300 会把这三个域的正常文件几乎全筛掉;
#   真要挡的是压缩 js / 内嵌 base64, 那种一行动辄上万字。
#
# 用法: bash gguf-tools/scripts/code_corpus_build.sh [raw 缓存目录]
#   默认缓存 gguf/go-onebit/code/raw(gguf/ 在 .gitignore 内; 每片 355 MB + pyarrow 虚拟环境); 已下的分片不重下,
#   产物目录每次整体重建。
set -uo pipefail
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
RAW="${1:-$ROOT/gguf/go-onebit/code/raw}"
OUT="$ROOT/gguf-tools/data/corpus/code"
BASE_URL="https://huggingface.co/datasets/codeparrot/github-code-clean/resolve/main/data"
MAX_SHARDS=10                 # 最多读到第 9 号分片(≈3.5 GB); 读完还有域不满就停
TARGET_BYTES=600000           # 每域必须凑满的字节(UTF-8)
DOC_CAP_CHARS=6000            # 单篇上限, 在行边界截断(截 4000 会把大部分 Java 文件截在 import 区)
MIN_CHARS=100                 # 空壳文件不要; Dockerfile/Makefile 正常文件就一两百字, 门槛不能再高
MAX_LINE_CHARS=1000           # 任一行超过它 = 压缩/生成的代码, 整篇不要
LOG(){ echo "[codecorpus $(date +%H:%M:%S)] $*"; }
DIE(){ LOG "★$*★"; exit 1; }
mkdir -p "$RAW"

if [ ! -x "$RAW/pyenv/bin/python" ]; then
    LOG "建 pyarrow 虚拟环境(只用来读 parquet, 不参与数值)"
    python3 -m venv "$RAW/pyenv" && "$RAW/pyenv/bin/pip" install -q pyarrow || DIE "pyarrow 安装失败"
fi

rm -rf "$OUT"; mkdir -p "$OUT"
# Python 只做文本编排(读 parquet/过滤/写 jsonl), 不参与任何数值; 分片下载也由它按需调 curl, 满额即停不多下。
"$RAW/pyenv/bin/python" - "$RAW" "$BASE_URL" "$OUT" "$MAX_SHARDS" "$TARGET_BYTES" "$DOC_CAP_CHARS" "$MIN_CHARS" "$MAX_LINE_CHARS" <<'PY' || DIE "抽取失败"
import json, os, re, subprocess, sys
import pyarrow.parquet as pq
raw, base, out = sys.argv[1], sys.argv[2], sys.argv[3]
MAXS, TARGET, CAP, MINC, MAXL = (int(x) for x in sys.argv[4:9])
# 域名 → 数据集 language 取值(数据集的全部 30 种; GO/FORTRAN 是数据集自己的大小写)
DOMAINS = [("code_assembly", "Assembly"), ("code_batchfile", "Batchfile"), ("code_c", "C"), ("code_csharp", "C#"),
           ("code_cpp", "C++"), ("code_cmake", "CMake"), ("code_css", "CSS"), ("code_dockerfile", "Dockerfile"),
           ("code_fortran", "FORTRAN"), ("code_go", "GO"), ("code_haskell", "Haskell"), ("code_html", "HTML"),
           ("code_java", "Java"), ("code_javascript", "JavaScript"), ("code_julia", "Julia"), ("code_lua", "Lua"),
           ("code_makefile", "Makefile"), ("code_markdown", "Markdown"), ("code_perl", "Perl"), ("code_php", "PHP"),
           ("code_powershell", "PowerShell"), ("code_python", "Python"), ("code_ruby", "Ruby"), ("code_rust", "Rust"),
           ("code_scala", "Scala"), ("code_shell", "Shell"), ("code_sql", "SQL"), ("code_tex", "TeX"),
           ("code_typescript", "TypeScript"), ("code_visual_basic", "Visual Basic")]
LANG2DOM = {l: d for d, l in DOMAINS}
LIC = re.compile(r"copyright|licen[cs]e|spdx", re.I)
GEN = re.compile(r"auto-?generated|do not edit|generated by", re.I)
# 开头注释块: /* */、<!-- -->、(* *) 三种块注释, 或连续的行注释(// # -- % ; ' ! :: rem, 可夹空行)
BLOCK = re.compile(r"\s*(?:/\*.*?\*/|<!--.*?-->|\(\*.*?\*\))[ \t]*\n", re.S)
LINES = re.compile(r"(?:[ \t]*(?://|#|--|%|;|'|!|::|[Rr][Ee][Mm]\b)[^\n]*\n|[ \t]*\n)+")

def strip_license(s):
    t = s.lstrip("﻿")
    head = ""
    if t.startswith("#!"):                       # shebang 保留, 从下一行起看
        nl = t.find("\n"); head, t = t[:nl + 1], t[nl + 1:]
    m = BLOCK.match(t) or LINES.match(t)
    if m and LIC.search(m.group(0)):
        t = t[m.end():].lstrip("\n")
    return head + t

def cap(s):
    if len(s) <= CAP: return s
    cut = s.rfind("\n", 0, CAP)
    return s[:cut if cut > CAP // 2 else CAP]

seen_repo = set()
docs = {d: [] for d, _ in DOMAINS}
size = {d: 0 for d, _ in DOMAINS}
for k in range(MAXS):
    if all(size[d] >= TARGET for d, _ in DOMAINS): break
    name = "train-%05d-of-00880.parquet" % k
    path = os.path.join(raw, name)
    if not os.path.exists(path):
        print("  下载 %s" % name, flush=True)
        subprocess.run(["curl", "-sfL", "-m", "1800", "-o", path + ".part", "%s/%s" % (base, name)], check=True)
        os.rename(path + ".part", path)
    t = pq.read_table(path, columns=["code", "repo_name", "language"])
    code, repo, lang = (t.column(c).to_pylist() for c in ("code", "repo_name", "language"))
    del t
    for c, r, l in zip(code, repo, lang):
        d = LANG2DOM.get(l)
        if d is None or size[d] >= TARGET or r in seen_repo: continue
        if GEN.search(c[:600]): continue
        s = cap(strip_license(c).replace("\r\n", "\n")).rstrip() + "\n"
        if len(s) < MINC or max(len(x) for x in s.split("\n")) > MAXL: continue
        seen_repo.add(r)
        docs[d].append(s); size[d] += len(s.encode())
    short = [d for d, _ in DOMAINS if size[d] < TARGET]
    print("  第 %d 片读完: 未满额 %d 域 %s" % (k, len(short), " ".join(short)), flush=True)

print("  %-18s %6s %10s" % ("域", "篇", "字节"))
for d, _ in DOMAINS:
    with open(os.path.join(out, d + ".jsonl"), "w", encoding="utf-8") as f:
        for s in docs[d]: f.write(json.dumps({"text": s}, ensure_ascii=False) + "\n")
    print("  %-18s %6d %10d" % (d, len(docs[d]), size[d]))
bad = [d for d, _ in DOMAINS if size[d] < TARGET]
assert not bad, "★读完 %d 片仍不满 %d 字节: %s★" % (MAXS, TARGET, bad)
PY
LOG "产物 $OUT: $(ls "$OUT" | wc -l | tr -d ' ') 个域, $(du -sh "$OUT" | cut -f1)"
LOG "CODE_CORPUS_DONE"
